### ISSUE TITLE
SFTP Sink: 'Permission denied' error

### ISSUE THREAD

**Issue by thucnguyen77** [Azure/Azure-DataFactory#153]
Hi,

Not sure if this is the right forum to report this SFTP Connector issue but it is being raised by many people here: https://feedback.azure.com/forums/270578-data-factory/suggestions/18742906-support-sftp-as-sink and didn't seem to get enough attention from MS team.

Personally I am facing following error.
```
DEBUG:
TraceComponentId: TransferTask
TraceMessageId: TransferRunFailed
@logId: Error
FunctionName: Execute
jobId: 3e00ccdd-6b18-b026-967f-e400f9de86b1
activityId: ea158102-4914-46ca-9e56-e1dc8ab3b8a5
eventId: TransferRunFailed
message: Copy failed with error: 'Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Permission denied to access '/Devt/INT-567a/xxxx.csv.ea158102491446ca9e56e1dc8ab3b8a5'.,Source=Microsoft.DataTransfer.ClientLibrary.SftpConnector,StackTrace=   at Microsoft.DataTransfer.ClientLibrary.SftpConnector.SftpFileSystem.WrapCommonSftpException(Exception ex, String filePath)
   at Microsoft.DataTransfer.ClientLibrary.SftpConnector.SftpFileSystem.WrapSftpException(String operation, Exception ex, String methodName, String filePath)
   at Microsoft.DataTransfer.ClientLibrary.SftpConnector.SftpFileSystem.RenameFile(String oldPath, String newPath, Boolean isPosix)
   at Microsoft.DataTransfer.ClientLibrary.SftpConnector.SftpMultipartSequentialWritable.<CommitAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DataTransfer.ClientLibrary.MultipartExtension.<RetryThrottleErrors>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DataTransfer.ClientLibrary.MultipartWriteSink.<ExecuteWithWorkingContext>d__84.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DataTransfer.ClientLibrary.MultipartWriteSink.<WriteStreamInSequentialAsync>d__85.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DataTransfer.ClientLibrary.MultipartWriteSink.<WriteStreams>d__74.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DataTransfer.ClientLibrary.MultipartWriteSink.Write(IEnumerable`1 dataReader)
   at Microsoft.DataTransfer.Runtime.SinkStageProcessor`1.ProcessInternal(IReadResult`1 data)
   at Microsoft.DataTransfer.Runtime.BinarySinkStageProcessor.ProcessInternal(IReadResult`1 data)
   at Microsoft.DataTransfer.Runtime.PipelineProcessStageProcessor`2.Process(TInput data)
   at Microsoft.DataTransfer.Runtime.PipelineProcessStageProcessor`2.Process(TInput data)
   at Microsoft.DataTransfer.Runtime.PipelineProcessStageProcessor`2.Process(TInput data)
   at Microsoft.DataTransfer.Runtime.PipelineProcessStageProcessor`2.Process(TInput data)
   at Microsoft.DataTransfer.TransferTask.CopyTask.DoCopy()
   at Microsoft.DataTransfer.TransferTask.CopyTaskBase.Execute(),''Type=Renci.SshNet.Common.SftpPermissionDeniedException,Message=Permission denied,Source=Renci.SshNet,StackTrace=   at Renci.SshNet.Sftp.SftpSession.RequestRename(String oldPath, String newPath)
   at Microsoft.DataTransfer.ClientLibrary.SftpConnector.SftpFileSystem.<>c__DisplayClass22_0.<RenameFile>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.DataTransfer.Common.Shared.HelperMethod.ExecuteWithTimeout(Action action, TimeSpan timeout, String timeoutErrorMessage)
   at Microsoft.Practices.TransientFaultHandling.RetryPolicy.<>c__DisplayClass1.<ExecuteAction>b__0()
   at Microsoft.Practices.TransientFaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at Microsoft.DataTransfer.ClientLibrary.RetryPolicyExtensionMethods.ExecuteActionWithTimeout(RetryPolicy retryPolicy, Action action, TimeSpan timeout, String timeoutErrorMessage)
   at Microsoft.DataTransfer.ClientLibrary.SftpConnector.SftpFileSystem.RenameFile(String oldPath, String newPath, Boolean isPosix),'
```
Hope to hear any feedback soon.

Cheers.

**Comment by fhljys** [comment]
Is this resolved?

**Comment by fhljys** [comment]
Close due to inactivity.
