### ISSUE TITLE
--app_arguments doesn't seem to work in spark job

### ISSUE THREAD

**Issue by vkupadya** [Azure/Azure-DataFactory#31]
When I run a job which specifies app_arguments like below to a spark job:

  "--app_arguments",
                "$$Text.Format('wasb://export@container.blob.core.windows.net/data/{0:yyyy}/{0:MM}/{0:dd}/{0:HH}/', SliceStart)",

I get below error.  I don't  see that this arg being handled in SparkJob.java. Am I missing something?

WARNING: Use "yarn jar" to launch YARN applications.
Jul 01, 2016 10:33:36 PM com.adf.spark.SparkJob run
SEVERE: Error while parsing arguments
org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: --app_arguments
    at org.apache.commons.cli.Parser.processOption(Parser.java:363)
    at org.apache.commons.cli.Parser.parse(Parser.java:199)
    at org.apache.commons.cli.Parser.parse(Parser.java:85)
    at com.adf.spark.SparkJob.run(SparkJob.java:89)
    at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
    at com.adf.spark.SparkJob.main(SparkJob.java:51)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
    at org.apache.hadoop.util.RunJar.main(RunJar.java:136)

Exception in thread "main" java.lang.RuntimeException: Error while parsing arguments:Unrecognized option: --app_arguments
    at com.adf.spark.SparkJob.run(SparkJob.java:98)
    at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
    at com.adf.spark.SparkJob.main(SparkJob.java:51)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
    at org.apache.hadoop.util.RunJar.main(RunJar.java:136)

**Comment by gauravmalhot** [comment]
Thanks for reporting this issue. We are working to release Spark as a first class activity in ADF in few weeks just like Hive and ADF. Stay tuned to Azure blog for updates.
