### ISSUE TITLE
@microsoft/azure-data-factory-utilities fails in Github Actions - Asking about Dynamics Connector

### ISSUE THREAD

**Issue by wjohnson** [Azure/Azure-DataFactory#383]
Using the `@microsoft/azure-data-factory-utilities` I am receiving the following error when executing the npm run command after installing the utilities package.  It's complaining about the Dynamics Connector but I am not using Dynamics in my copy activities. Just blob to blob copy.  Any guidance on how to resolve the issue would be greatly appreciated!

I'm creating a public demo which you can browse here: https://github.com/[wjohnson/ADFDeployInGithub](https://github.com/wjohnson/ADFDeployInGithub)

## Error Message
```bash
Run npm run build export ./adf $GITHUB_DEV_ADF_RESOURCE_ID ArmTemplateOutput

> build
> node node_modules/@microsoft/azure-data-factory-utilities/lib/index "export" "./adf" "ArmTemplateOutput"

Downloading bundle from: https://adf.azure.com/assets/cmd-api/main.js
Process cwd: /home/runner/work/ADFDeployInGithub/ADFDeployInGithub
Bundle downloaded successfully, saved in: /home/runner/work/ADFDeployInGithub/ADFDeployInGithub/downloads/main.js
Executing bundle...
Inserting the following arguments: export ./adf ArmTemplateOutput
Executing bundle file, full command:

node  /home/runner/work/ADFDeployInGithub/ADFDeployInGithub/downloads/main.js export ./adf ArmTemplateOutput



 CmdApiApp: Initializing application.
/home/runner/work/ADFDeployInGithub/ADFDeployInGithub/node_modules/@microsoft/azure-data-factory-utilities/lib/bundle.manager.js:53
                    throw "Execution failed with exit code: " + exitCode;
                    ^
Execution failed with exit code: 255
(Use `node --trace-uncaught ...` to show where the exception was thrown)
Resource: ArmTemplateOutput
RootFolder: ./adf
 ModelService: synchronize - start
 ModelService: Dynamic connector - Start registering dynamic connectors
 ERROR === DynamicConnectorService: Dynamic connector - Error happens when loading dynamic connectors from adf resource: Cannot find module './550.js'
Require stack:
- /home/runner/work/ADFDeployInGithub/ADFDeployInGithub/downloads/main.js
 CmdApiApp: Initializing resource registries...
 CmdApiApp: Initializing model service...
 ModelService: Dynamic connector - Finished registering dynamic connectors
 BaseFileResourceProviderService: populateAllResources - start
 CmdApiApp: Initializing publish config service...
 PublishConfigService: _getLatestPublishConfig - retrieving config file.
 LocalFileClientService: Unable to list files for: integrationRuntime, error: Error: ENOENT: no such file or directory, scandir 'adf/integrationRuntime'
 LocalFileClientService: Unable to list files for: trigger, error: Error: ENOENT: no such file or directory, scandir 'adf/trigger'
 LocalFileClientService: Unable to list files for: factory, error: Error: ENOENT: no such file or directory, scandir 'adf/factory'
 LocalFileClientService: Unable to list files for: dataflow, error: Error: ENOENT: no such file or directory, scandir 'adf/dataflow'
 LocalFileClientService: Unable to list files for: credential, error: Error: ENOENT: no such file or directory, scandir 'adf/credential'
 LocalFileClientService: Unable to list files for: managedVirtualNetwork, error: Error: ENOENT: no such file or directory, scandir 'adf/managedVirtualNetwork'
 ERROR === LocalFileClientService: Unable to read file: adf/publish_config.json, error: {"stack":"Error: ENOENT: no such file or directory, open 'adf/publish_config.json'","message":"ENOENT: no such file or directory, open 'adf/publish_config.json'","errno":-2,"code":"ENOENT","syscall":"open","path":"adf/publish_config.json"}
 ERROR === PublishConfigService: _getLatestPublishConfig - Unable to process publish config file, error: {"stack":"Error: ENOENT: no such file or directory, open 'adf/publish_config.json'","message":"ENOENT: no such file or directory, open 'adf/publish_config.json'","errno":-2,"code":"ENOENT","syscall":"open","path":"adf/publish_config.json"}
 CmdApiApp: App initialized.
 BaseFileResourceProviderService: populateAllResources - downloaded git resources
 BaseFileResourceProviderService: populateAllResources - loaded last version id
 BaseFileResourceProviderService: populateAllResources - finished
 ModelService: fetchAllInBackground - start
 ModelService: synchronize - finished
 CmdApiApp: Starting to validate all resources
 ModelService: _backgroundFetch - finished, duration: 56.8[4](https://github.com/wjohnson/ADFDeployInGithub/runs/6369921811?check_suite_focus=true#step:6:4)70[5](https://github.com/wjohnson/ADFDeployInGithub/runs/6369921811?check_suite_focus=true#step:6:5)199999735, total nameds: 5
 ERROR === CmdApiApp: Failed to run resource validation. Error: {"stack":"TypeError: Cannot read properties of undefined (reading 'concept')\n    at Function.<anonymous> (/home/runner/work/ADFDeployInGithub/ADFDeployInGithub/downloads/main.js:2:[6](https://github.com/wjohnson/ADFDeployInGithub/runs/6369921811?check_suite_focus=true#step:6:6)212[8](https://github.com/wjohnson/ADFDeployInGithub/runs/6369921811?check_suite_focus=true#step:6:8)52)\n    at /home/runner/work/ADFDeployInGithub/ADFDeployInGithub/downloads/main.js:2:2155800\n    at Object.next (/home/runner/work/ADFDeployInGithub/ADFDeployInGithub/downloads/main.js:2:2155[9](https://github.com/wjohnson/ADFDeployInGithub/runs/6369921811?check_suite_focus=true#step:6:9)05)\n    at a (/home/runner/work/ADFDeployInGithub/ADFDeployInGithub/downloads/main.js:2:2154644)","message":"Cannot read properties of undefined (reading 'concept')"}
 ERROR === CmdApiApp: Failed to export ARM template. Error: {"stack":"TypeError: Cannot read properties of undefined (reading 'concept')\n    at Function.<anonymous> (/home/runner/work/ADFDeployInGithub/ADFDeployInGithub/downloads/main.js:2:62[12](https://github.com/wjohnson/ADFDeployInGithub/runs/6369921811?check_suite_focus=true#step:6:12)852)\n    at /home/runner/work/ADFDeployInGithub/ADFDeployInGithub/downloads/main.js:2:2[15](https://github.com/wjohnson/ADFDeployInGithub/runs/6369921811?check_suite_focus=true#step:6:15)5800\n    at Object.next (/home/runner/work/ADFDeployInGithub/ADFDeployInGithub/downloads/main.js:2:[21](https://github.com/wjohnson/ADFDeployInGithub/runs/6369921811?check_suite_focus=true#step:6:21)55905)\n    at a (/home/runner/work/ADFDeployInGithub/ADFDeployInGithub/downloads/main.js:2:21546[44](https://github.com/wjohnson/ADFDeployInGithub/runs/6369921811?check_suite_focus=true#step:6:44))","message":"Cannot read properties of undefined (reading 'concept')"}


=====ERROR=====
Error: Command failed: node  /home/runner/work/ADFDeployInGithub/ADFDeployInGithub/downloads/main.js export ./adf ArmTemplateOutput

Execution finished....
Error: Process completed with exit code 1.
```

## Github Action workflow
```yaml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Set up Node, I've tried Node 10 as in the docs as well
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      # Run the npm run build export command
      - name: Run a one-line script
        run: npm run build export ./adf $GITHUB_DEV_ADF_RESOURCE_ID ArmTemplateOutput
```

**Comment by fhljys** [comment]
Can you replace $GITHUB_DEV_ADF_RESOURCE_ID with a real factory resource id "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/testResourceGroup/providers/Microsoft.DataFactory/factories/DevDataFactory"
