### ISSUE TITLE
SSIS Package execution fails if SSISIR is in a different region to datafactory AND ConnectByProxy is TRUE

### ISSUE THREAD

**Issue by iwctm** [Azure/Azure-DataFactory#503]
We have a data factory setup in West US 2 with a SSIS IR located in South UK and a Self Hosted IR also in the UK. If we have a SSIS package with a connection that has the ConnectByProxy set to TRUE then the package fails with the following errors:

```
Error: ConnectByProxy: Request staging task with operation guid (null) fail since error: Failed to dispatch staging operation with error message: System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.SqlServer.IntegrationServices.AisAgentCore.TaskManagement.AisOperationServiceClient.<>c__DisplayClass22_0.<StartStagingExecution>b__0() in C:\__w\1\s\Product\Source\Everest\Worker\AgentHost\AisAgentCore\TaskManagement\AisOperationServiceClient.cs:line 242
   at Microsoft.SqlServer.IntegrationServices.ScaleOut.Utilities.TryHelper.Retry(Action action, String message, Int32 retryCount, TimeSpan retryInterval, Boolean throwOnRetryFail)
   at Microsoft.SqlServer.IntegrationServices.AisAgentCore.TaskManagement.AisOperationServiceClient.StartStagingExecution(Guid operationGuid, StagingExecutionInfo stagingExecutionInfo) in C:\__w\1\s\Product\Source\Everest\Worker\AgentHost\AisAgentCore\TaskManagement\AisOperationServiceClient.cs:line 245
   at Microsoft.SqlServer.IntegrationServices.AisAgentCore.AisOperationDispatcherProxy.DispatchStagingOperation(Guid operationGuid, StagingExecutionInfo stagingExecutionInfo) in C:\__w\1\s\Product\Source\Everest\Worker\AgentHost\AisAgentCore\AisOperationDispatcherProxy.cs:line 35
   at Microsoft.SqlServer.IntegrationServices.WorkerAgent.PackageExecutionTaskTracker.StartLoadStagingData(StagingExecutionInfo stagingExecutionInfo, OperationDispatcherProxy operationDispatcherProxy)
```

```
Error: The Execute method on the task returned error code 0xC020F460 (ConnectByProxy: Request staging task with operation guid (null) fail since error: Failed to dispatch staging operation with error message: System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.SqlServer.IntegrationServices.AisAgentCore.TaskManagement.AisOperationServiceClient.<>c__DisplayClass22_0.<StartStagingExecution>b__0() in C:\__w\1\s\Product\Source\Everest\Worker\AgentHost\AisAgentCore\TaskManagement\AisOperationServiceClient.cs:line 242
   at Microsoft.SqlServer.IntegrationServices.ScaleOut.Utilities.TryHelper.Retry(Action action, String message, Int32 retryCount, TimeSpan retryInterval, Boolean throwOnRetryFail)
   at Microsoft.SqlServer.IntegrationServices.AisAgentCore.TaskManagement.AisOperationServiceClient.StartStagingExecution(Guid operationGuid, StagingExecutionInfo stagingExecutionInfo) in C:\__w\1\s\Product\Source\Everest\Worker\AgentHost\AisAgentCore\TaskManagement\AisOperationServiceClient.cs:line 245
   at Microsoft.SqlServer.IntegrationServices.AisAgentCore.AisOperationDispatcherProxy.DispatchStagingOperation(Guid operationGuid, StagingExecutionInfo stagingExecutionInfo) in C:\__w\1\s\Product\Source\Everest\Worker\AgentHost\AisAgentCore\AisOperationDispatcherProxy.cs:line 35
   at Microsoft.SqlServer.IntegrationServices.WorkerAgent.PackageExecutionTaskTracker.StartLoadStagingData(StagingExecutionInfo stagingExecutionInfo, OperationDispatcherProxy operationDispatcherProxy)
). The Execute method must succeed, and indicate the result using an "out" parameter.
```
 
We can get the package to execute without error if we change the location of the SSIS-IR to the same region as the datafactory, however, performance is terrible (a package that takes a few minutes to run on my local machine takes 6 hrs up in Azure).

Our setup was previously working up until 1-2 months ago.

**Comment by jarodzhu** [comment]
This is a product bug introduced last month and we have fixed it in service today. Please check whether the issue has been resolved in your side.

**Comment by iwctm** [comment]
Just confirming that this is indeed resolved.
